apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st Container
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/sasi/html
  - name: 2nd Container
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/date-index.html;
          sleep 1;
        done
